name: Node.js CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            architecture: x64
          - os: macos-latest
            target: aarch64-apple-darwin
            architecture: arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            architecture: x64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            architecture: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          architecture: ${{ matrix.architecture }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: stable
          target: ${{ matrix.target }}
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: ls -l -a -h
      - uses: actions/upload-artifact@v3
        with:
          name: bindings-${{ matrix.target }}
          path: native-certs.*.node
          if-no-files-found: warn
