name: Node.js CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            architecture: x64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            architecture: x64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            architecture: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          architecture: ${{ matrix.architecture }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test

