name: Node.js CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: darwin-x64
            architecture: x64
          - os: windows-latest
            target: win32-x64-msvc
            architecture: x64
          - os: ubuntu-latest
            target: linux-x64-gnu
            architecture: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          architecture: ${{ matrix.architecture }}
      - run: npm install
      - run: npm run build --target ${{ matrix.target }}
      - run: npm test

